### ISSUE TITLE
Issues with MySQL test cases

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-core#100]
- [ ] RMLTC0018a-MySQL The test assumes that MySQL is ANSI SQL compliant, but it is not. MySQL does trim trailing spaces. Hence the test will wrongly accuse of engines not to produce correct RDF. I would suggest removing RMLTC0018a-MySQL. 
- [ ] RMLTC0015a-MySQL The JDBC URL in the mapping does not set the sql-mode to ANSI_SQL. This test case thus assumes that this SQL mode is enabled on the server. This is not only be default not the case, but the community encourages not to do so as it can be specified at connection level. So options here are: remove the test, add the sql mode in the jdbc connection url, or explicitely state all assumptions of the MySQL server.
- [x] RMLTC0002f-MySQL seems to be a valid mapping. Everything matches (table name, and column names).
- [x] RMLTC0003b-MySQL needs to return an error (and thus no output file with triples) as the source contains both a table name and a query.

**Comment by chrdebru** [comment]
1) Yes. Either remove the tests for MySQL. Or have something that would pass for them and write a note. RML engine should try and support PostgreSQL (which is more ANSI compliant).
2) I'm pretty sure 2f is not wrong
3) I proposed a fix for 3b. The output of 3b was not empty. All other failing mappings had empty output files. So, I believe that the additional `rml:tableName` was a copy-paste error. :-) It makes sense, as the reference relied on a derived attribute (concatenate). In other words, 3b is fixed.

**Comment by pmaria** [comment]
Some other issues:

`rml:SQL2008TableName` is used vs `rml:SQL2008Table` (in io spec)
`rml:tableName` used but not described io spec
`rml:sqlVersion` used but described io spec

Actions:
- [ ] replace `rml:SQL2008TableName` with  `rml:SQL2008Table`
- [ ] remove `rml:tableName` and `rml:sqlVersion`

**Comment by pmaria** [comment]
2f should use delimited identifiers as in https://www.w3.org/2001/sw/rdb2rdf/test-cases/#R2RMLTC0002f

**Comment by pmaria** [comment]
- [ ] RMLTC0012b-MySQL missing reference formulation

**Comment by pmaria** [comment]
I'm leaning towards dropping RMLTC0018a entirely due to the different behavior of databases and this rather niche case. Agreed @chrdebru @DylanVanAssche ?

**Comment by DylanVanAssche** [comment]
+1 for dropping 18a

**Comment by chrdebru** [comment]
Agree on dropping 18a.

**Comment by bjdmeest** [comment]
agree on dropping 18a too. But we probably want an IO test to cover "Description: Generation of triples by using CHAR datatype column, resulting RDF literal is space-padded. ([specification reference](http://www.w3.org/TR/r2rml/#from-template))" at a later stage. Tracked at https://github.com/kg-construct/rml-io/issues/41 so this issue can be closed after stuff is fixed
