### ISSUE TITLE
Error in spec about referencing attributes when processing XML

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-core#103]
The specification only contains one example of selecting an XML attribute, but I'm fairly certain it is wrong:

```
[] rml:objectMap [
  rml:reference "Localization" ;
  rml:languageMap [
    rml:reference "Localization[@Culture]" ;
  ] ;
] .
```

Should be

```
[] rml:objectMap [
  rml:reference "Localization" ;
  rml:languageMap [
    rml:reference "Localization/@Culture" ;
  ] ;
] .
```

As `Localization/@Culture` selects the value of the attribute `Culture` from the element and the former is used to select only localizations with a culture attribute.

**Comment by DylanVanAssche** [comment]
Yeah I think you're right, let's assign the maintainers.
