### ISSUE TITLE
Term Map definition in RML core 

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#12]
I get what you mean, it's also inherited reasoning from RML, but if we want to finally be 100% correct, we do need a superclass that allows us to bring everything correct. Then we would have something like this

* `rml:newSuperTermMap`
  * `rml:TermMap`
  * `rr:TermMap`
  * `fnml:FunctionMap`

where `rml:TermMap`, `rr:TermMap` and `fnml:FunctionMap` are subclasses of the newSuperTermMap

and that would also make everything more correct because the Term Map is actually abused in the case of RML, as an `rr:TermMap` should have one of column/template/reference and not reference that the `rml:TermMap` should have.

RML was on purposed designed to abuse R2RML vocab, but as it is now, the cleanest solution would be to revise the RML vocabulary to correctly generalize R2RML.

If we make things valid, ie as explained above, then I think the best would be to straight go for a correct definition of `fnml:FunctionMap`

(it might even be like the following, ie the `rr:TermMap` a subclass of `rml:TermMap` but that might not matter for the discussion here
* `rml:newSuperTermMap`
  * `rml:TermMap`
    * `rr:TermMap`
  * `fnml:FunctionMap`)

_Originally posted by @andimou in https://github.com/kg-construct/rml-fno-spec/issues/11#issuecomment-809192721_

**Comment by andimou** [comment]
A couple more relevant comments from #11:

https://github.com/kg-construct/rml-fno-spec/issues/11#issuecomment-809187133 by @bjdmeest 

https://github.com/kg-construct/rml-fno-spec/issues/11#issuecomment-809192721 by @andimou 

https://github.com/kg-construct/rml-fno-spec/issues/11#issuecomment-809270023 by @pmaria

**Comment by andimou** [comment]
@bjdmeest @samiscoding does this hold with the new FnO?

**Comment by bjdmeest** [comment]
Current status: https://kg-construct.github.io/fnml-spec/#function-valued-term-map

> A [function-valued term map](https://kg-construct.github.io/fnml-spec/#dfn-function-valued-term-map) is a [term map](https://kg-construct.github.io/fnml-spec/#dfn-term-map) that is represented by a resource that has exactly one fnml:execution. The value of the fnml:execution property must be a valid [FNML Execution](https://kg-construct.github.io/fnml-spec/#dfn-fnml-execution).

Hence, it's on the same level as, e.,g., a template-valued term map. As long as templates are not affected, neither are functions.

**Comment by DylanVanAssche** [comment]
Okay, but do you have a suggestion to fix this? The spec is now visible at http://w3id.org/rml/core/spec which makes discussing so much easier.

**Comment by andimou** [comment]
I think there is a Term Map definition in the spec now. Would you like to have a look so we can close this issue?

**Comment by bjdmeest** [comment]
My comment got resolved, so this can be closed!
