### ISSUE TITLE
Define Logical Source in RML-Core instead of RML-IO

### ISSUE THREAD

**Issue by pmaria** [kg-construct/rml-core#127]
Currently the concept of a Logical Source is [defined and described in the RML-IO spec](https://w3id.org/rml/io/spec#source-vocabulary). 

However, there are many mentions to logical source in definitions of RML-Core constructs. Not having Logical Source defined in core makes it difficult to describe these constructs properly.

**Proposal**:
Describe Logical Source in the abstract sense in core. Describe the notion of iterations and reference formulations here, in an abstract sense, such that these concepts can be used to properly define the relevant core concepts.

Note: Some discussion around this topic has also taken place in the context of https://github.com/kg-construct/rml-lv/issues/14

**Comment by bjdmeest** [comment]
AGREEMENT 03/07: @pmaria will create a suggestion
