### ISSUE TITLE
multiple values

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#13]
Do we already have any specifications in the case of having a list of output values? I think it falls more into the behavior of the engine but still makes sense to have the definition of the correct behavior.

_Originally posted by @samiscoding in https://github.com/kg-construct/rml-fno-spec/issues/7#issuecomment-810846015_

how do we handle multiple values in RML?

Related to https://github.com/kg-construct/mapping-challenges/tree/main/challenges/multivalue-references

**Comment by andimou** [comment]
multiple values are created if it's not a gather map

**Comment by dachafra** [comment]
I think all clarifications about multi-values have been integrated into the spec. This can be closed now.
