### ISSUE TITLE
Miss-Alignment between the shapes in https://kg-construct.github.io/rml-core/ontology/rml-core-bc.ttl and R2RML specification

### ISSUE THREAD

**Issue by alloka** [kg-construct/rml-core#130]
Hello All,

In the backward compatibility shapes, it is mentioned that the R2RML Predicate-Object Map is an owl:subpropertyof the RML  Predicate-Object Map, while it is defined to be one or more in RML, in the R2RML specification the Predicate-Object Map is actually zero or more. I will also check the rest of the shapes and comment further on this issue if there are more.

Best Regards,
Ali

**Comment by pmaria** [comment]
@alloka could you point to where it is defined to be one or more in RML? If that is the case, it is a mistake.

**Comment by alloka** [comment]
@pmaria here: https://kg-construct.github.io/rml-core/shapes/core.ttl

**Comment by pmaria** [comment]
@alloka 
I only see this shape, in which it seems to be correct:

```turtle
[ sh:description """
        A Predicate Object Map element to generate a (predicate, object) pair.
        """ ;
            sh:message """
        rml:PredicateObjectMap must be an IRI or blank node.
        """ ;
            sh:minCount 0 ;
            sh:name "predicateObjectMap" ;
            sh:nodeKind sh:BlankNodeOrIRI ;
            sh:path rml:predicateObjectMap ;
            sh:targetSubjectsOf rml:predicateObjectMap ]
```

The source for the linked shapes is: https://github.com/kg-construct/rml-core/blob/dd2c79428b5ae1702a3f1f4104b7b7977db32728/shapes/core.ttl#L510

Could you give a permalink to the offending lines in that file?

**Comment by alloka** [comment]
@pmaria my bad, I must have mixed it with another definition, I'm going to close the issue :)
