### ISSUE TITLE
Replace `sh:name` and `sh:description` in SHACL shapes

### ISSUE THREAD

**Issue by marioscrock** [kg-construct/rml-core#139]
The usage of `sh:name` and `sh:description` should be replaced with `rdfs:label` and `rdfs:comment` since their domain is limited to PropertyShape. Cf. https://github.com/w3c/data-shapes/issues/145

**Comment by DylanVanAssche** [comment]
Oh this is the case for all repositories then...

**Comment by DylanVanAssche** [comment]
Made PRs in all RML specs for this, please review.
