### ISSUE TITLE
empty literals 

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#16]
should we generate a triple for empty literals?

if so, when should we do that?

**Comment by chrdebru** [comment]
Do you mean the empty string ε? In CS, the empty string is different `null` [1]. Given that in CSV files `...,,...` yield `null` and `...,"",...` yields an empty string, I would argue to generate a triple with an empty literal as the default behavior. This would correspond with the behavior one has in programming and query languages. One can use functions (either with fno or in the query) for "cleaning up" the data.

[1] https://en.wikipedia.org/wiki/Empty_string

**Comment by dachafra** [comment]
I would say that the default behavior should be exactly the other way around. If there is an empty string, the triple shouldn't be generated (I think is the usual behavior from most of the engines), but engines can be configured to do it in the case the users want that triples in the graph

**Comment by bjdmeest** [comment]
> I would say that the default behavior should be exactly the other way around. If there is an empty string, the triple shouldn't be generated (I think is the usual behavior from most of the engines), but engines can be configured to do it in the case the users want that triples in the graph

I agree with @chrdebru though: `null` is different from `""`, and default behavior of r2rml is to look at `NULL`, which is (in SQL) different from `""` too. I vote for default behavior: `NULL` -> skip term, `""` generate term with empty string.
We have a precedent issue in the mapper: https://github.com/RMLio/rmlmapper-java/issues/140, with distinction between `""` and `NULL` needed

However, we could define some options that we give to the engine, this being one of them

**Comment by dachafra** [comment]
But for example in CSV we do not have the NULL concept, how we specify that we don't want to generate a value for an empty cell?. As far as I understood the behavior (for a cell value in a CSV) could be:
- ,NULL, --> skip term
- ,"", -> generate term
- ,, -> skip term?

**Comment by bjdmeest** [comment]
During the Ghent meeting we stated that `,,` is `NULL`, different from `,"",`, which is `""`. Which we [handle as such](https://github.com/RMLio/rmlmapper-java/blob/master/src/main/java/be/ugent/rml/records/CSVRecordFactory.java#L145) in the mapper using the OpenCSV library (which has an option to do so)

In CSVW, they specify that `,,` and `""` both denote the empty string, so they don't differentiate between the two. As long as we find a way to differentiate between the two, all fine for me ;).

In CSVW, they have a flag `csvw:null` to denote if a value should be handled as NULL. If we have support for that and are able to differentiate between `EMPTY_SEPARATORS` (cfr. OpenCSV library) and `""`, then I think we can support all use cases :)

**Comment by dachafra** [comment]
So we have a proposal:
1) Update the core spec clarifying the default behavior of empty values in CSVs, JSON, XML, etc
2) Update the LogicalSource spec to allow the use of `csvw:null`, @DylanVanAssche could you open an issue for you in the corresponding repo?

**Comment by DylanVanAssche** [comment]
@dachafra 

> Update the LogicalSource spec to allow the use of csvw:null, @DylanVanAssche could you open an issue for you in the corresponding repo?

This is already allowed for CSV, see https://rml.io/docs/rml/data-retrieval/ because in CSV you can have:

- `""`
- `,,`
- `"NULL"`
- `"null"`
- `"$YOUR_NULL_ID"`

These are specified under `rml:source`, so you need a proper ontology there (it is rather open to anything).
Would be weird to specify a CSVW file there for JSON, just to be able to use `csvw:null` :sweat_smile: 
If we want to generalize that, we may need to extend DataIO to include such a description: https://rml.io/specs/dataio.
That spec is especially designed for such things: describing various sources under `rml:source` or `rmlt:target`.

**Comment by dachafra** [comment]
Ok, agree on not using `csvw:null` for JSON or XML (actually I didn't ask for it jeje)
Indeed, that is a problem in the LogicalSource or in DataIO spec (which is outside the w3c group), **so from the core perspective we only need to specify the default behavior for empty values**

**Comment by DylanVanAssche** [comment]
Created an issue in the rml-target-source-spec so we don't lose track of this.

**Comment by andimou** [comment]
> Update the core spec clarifying the default behavior of empty values in CSVs, JSON, XML, etc

That would not be 100% correct because in the core we don't aim to describe all possible behaviours but indicating what the default means, therefore something along the lines:

1. Update the core spec clarifying the default behavior of empty values in each data format is what each format's specification indicates.

and then give examples for CSV, XML and JSON which are the most frequently used.

**Comment by DylanVanAssche** [comment]
@chrdebru 

> E.g., will a '' from a relational database become a NULL when combined with a CSV file? Do models "inherit" from one or the other source model? We agreed to take note of this issue.

I would expect that it is inherited from the Logical Source description from where that data value comes from

> Update the core spec clarifying the default behavior of empty values in each data format is what each format's specification indicates.

+1

**Comment by DylanVanAssche** [comment]
`rml:null` exists in RML-IO to specify what empty is for the Source.

Is the Core part also incorporated in the new version? e.g. what to do when empty?

**Comment by andimou** [comment]
A clarification was added in this commit 552a485353a9c3eb0e45f3025c22d53e7c01e312 would you like to have a look if it is enough?

**Comment by DylanVanAssche** [comment]
> A clarification was added in this commit https://github.com/kg-construct/rml-core/commit/552a485353a9c3eb0e45f3025c22d53e7c01e312 would you like to have a look if it is enough?

It looks better yes, would incorporate the suggestion of @bjdmeest  though.

PS:
Can we please do all of this as PRs, one feature == 1 PR. Commits in separate branches are unreviewable because these comments are hidden unless you know the exact commit. This would make reviewing so much easier, thanks!!

**Comment by DylanVanAssche** [comment]
Will be merged as part of https://github.com/kg-construct/rml-core/pull/128
