### ISSUE TITLE
subject is IRI?

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#24]
The R2RML spec says

> The subjects often are IRIs that are generated from the primary key column(s) of the table.

does this often refer to the IRIs or the primary key column? 

I would think that this would be translate to 

> The subjects ~often~ are IRIs ~that are generated from the primary key column(s) of the table~.

or could they be anything else as well?

**Comment by pmaria** [comment]
I think the "often" in

> The subjects often are IRIs that are generated from the primary key column(s) of the table.

refers to both IRIs and primary key columns.

So the subjects are often IRIs and are often generated from the primary key column(s) of the table.

But a subject can definitely also be a blank node, or in RDF star world a triple. 
That would be it, unless we want to foray into generalized RDF...

**Comment by dachafra** [comment]
I think we also have a proposal here right?

- Update the R2RML description about `subject` generation beyond IRIs (although I would be more in favor to refer the RDF spec directly)
- Remove the fact that subjects are generated from a PK column. The sentence could be generalized

**Comment by andimou** [comment]
this is related to #30

**Comment by andimou** [comment]
I think this is resolved on its own?

**Comment by dachafra** [comment]
I think this can be closed
