### ISSUE TITLE
all potential combinations to generate all possible outputs

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#26]
After our discussions, I created an Excel sheet where we can include all possible combinations.

The excel sheet is available at https://docs.google.com/spreadsheets/d/163K5XoeudPyvEWzlc9oTRqPwHCwGHUopu4mJMGPndR0/edit

I create this issue to provide the link and use it as reference for other issues that refer to this Excel sheet but discuss more detailed topics

**Comment by DylanVanAssche** [comment]
This issue is not a problem or discussion, but a note. Can we incorporate this elsewhere?

**Comment by dachafra** [comment]
can we close this issue? @andimou @DylanVanAssche
