### ISSUE TITLE
no section of default mapping generator in RML-core

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#33]
The R2RML spec includes the following paragraph for duplicates handling:

> Duplicate row preservation: For tables without a primary key, the Direct Graph requires that a fresh blank node is created for each row. This ensures that duplicate rows in such tables are preserved. This requirement is relaxed for R2RML default mappings: They MAY reuse the same blank node for multiple duplicate rows. This behaviour does not preserve duplicate rows. R2RML default mapping generators that provide default mappings based on the Direct Graph MUST document whether the generated default mapping preserves duplicate rows or not.

This needs to be adjusted in the case of heterogeneous data

**Comment by dachafra** [comment]
But here is talking about handling duplicate rows in R2RML when subjectMap is a blank node, what does it need to be adjusted for heterogeneous data? (apart from generalizing the "row" concept)

**Comment by andimou** [comment]
btw, I think this is an rml-core issue rather than an rml-fno issue

**Comment by pmaria** [comment]
This is about default mapping generation. 

IMO the first question to answer here is: are we going to specify default mapping generation in RML?

**Comment by pmaria** [comment]
I think we still need to decide whether or not default mappings are a thing we want to maintain as part of RML. 

Are there any current implementations of default mapping generators?

**Comment by dachafra** [comment]
@pmaria if you refer to this R2RML section (https://www.w3.org/TR/r2rml/#default-mappings), I'll remove it for RML. No current implementation of R2RMl or RML has default mapping generators. There were engines like MIRROR https://github.com/oeg-upm/MIRROR, but afaik they were deprecated

**Comment by pmaria** [comment]
Yes, that's what I'm referring too.

I also agree that we can remove this from the spec. 
If we all agree on this, this issue can be closed, since the issue is about default mapping generators.

**Comment by dachafra** [comment]
@bjdmeest @andimou @DylanVanAssche @chrdebru @frmichel do you agree with this proposal? i.e. no section of default mapping generator in RML-core?

**Comment by pmaria** [comment]
We still need to update the spec. Let's keep this issue open until that is done.

**Comment by dachafra** [comment]
PR with the removal #133
