### ISSUE TITLE
reference definition

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#34]
We need to agree on how we are going to call the `rml:reference` values.

**Comment by dachafra** [comment]
what was the discussion? (i.e., what are the other possibilities?) @andimou

**Comment by dachafra** [comment]
is there still any discussion around this?

**Comment by DylanVanAssche** [comment]
I think there's a definition in the latest version? Can we confirm this? If so, we can close this.

**Comment by DylanVanAssche** [comment]
Checked the spec, there's a definition for a reference. Closing.
