### ISSUE TITLE
Developer-friendly DSL as part of the RML specification?

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/rml-core#49]
Many comment on RML as being verbose. RML mappings do not necessarily need to be crafted by hand, and multiple [DSL](https://en.wikipedia.org/wiki/Domain-specific_language)-like languages have emerged, such as [ShexML](http://shexml.herminiogarcia.com/) and [YARRRML](https://rml.io/yarrrml/spec/).
I propose to standardize (after RML is 'complete') a human-friendly way to edit RML documents, as these previous languages have shown that this will increase uptake of the spec.

Similar efforts: [SHACL compact syntax](https://w3c.github.io/shacl/shacl-compact-syntax/)

**Comment by dachafra** [comment]
I think that YARRRML will be extended with the new RML concepts and properties. 

@bjdmeest is there any way to have the current version of YARRRML spec in a repo here? So we could update it when we have our new specs finished

**Comment by bjdmeest** [comment]
I pushed a fork to https://github.com/kg-construct/yarrrml-spec for the time being! :)

**Comment by dachafra** [comment]
Awesome! I think we can close this issue
