### ISSUE TITLE
CI/CD workflows for spec repositories

### ISSUE THREAD

**Issue by pmaria** [kg-construct/rml-core#54]
Proposal sketched up with @DylanVanAssche for CI/CD workflows for the spec repositories, to keep specs and ontology/shapes in line, and also do some automatic validations / generation where applicable.

## shapes coverage test

Create a GitHub action to be used by all spec repo's that contains generic CI/CD functionality.
As input the action 0 or more other spec-repositories can be specified on which this spec-repo is dependent. 

The action then collects the necessary artefacts from the repo's and executes the following steps:

1. Syntax-validation/parse ontologies (if error is encountered give clear msg with offending repo and file)
1. Validate / Test shapes
1. Validate examples

All spec repo's get the following directory structure

```
[spec-repo]
├── model/
│   ├── ontology/       # Ontology reflecting the spec ( this will be combined with rml-core and possibly other specs )
│   └── shapes/         # Shapes reflecting the spec
│       └── tests/      # Test cases which cover the shapes
└── examples/           # Examples used in the spec
```

Under `model/shapes/tests` we have test cases that cover the shapes reflecting the spec developed in the current repo.
This helps us ensure that our shapes and ontology are valid and stay up to date with the spec.

Under `examples/` we have all examples that are used in the text of the spec. We place them in this standard location
so that they can also be validated against the shapes used in the previous step.

On each push to any branch, these tests will be run.

## PR templates

We will introduce PR templates including a checklist which reminds us to:
* make sure that the model is in sync with the spec.

## Generate combined model

We can introduce a merge action which triggers a commit or PR to update the full model (in rml-core repo?)

**Comment by DylanVanAssche** [comment]
Update: CI/CD is merged with SHACL shapes and test-cases so we're almost there for all specs.
