### ISSUE TITLE
IRIs for modules

### ISSUE THREAD

**Issue by anaigmo** [kg-construct/rml-core#58]
Since we are adopting solution (3) from #56, we need to decide the namespace for each module. Here is a first proposal:
* Base for all resources: http://w3id.org/rml/ 
* Core: http://w3id.org/rml/core/
* Source & Target: http://w3id.org/rml/source-target/
* Collections and Containers: http://w3id.org/rml/collections-containers/
* FNML: http://w3id.org/rml/fnml/
* RML-star: http://w3id.org/rml/star/

Any suggestion of change of any module is welcome

**Comment by pmaria** [comment]
By namespace for each module I assume you mean IRI right?
 
I don't think there is a need to create any resources under the module namespace, right? Or am I missing something?

**Comment by anaigmo** [comment]
Yes, I mean IRI. All the resources are created with the base IRI, but then we assign each of them to its correspondent module. For instance, rml:TriplesMap is assigned to http://w3id.org/rml/core/; rml:LogicalTarget to http://w3id.org/rml/source-target/ --> This way we differentiate to which module each resource belongs to; so we need an IRI for each module in order to do this

**Comment by DylanVanAssche** [comment]
I don't have a strong opinion here. I like the original proposal.

**Comment by frmichel** [comment]
I agree that this is rather long (source-target and collections-containers) but I don't really see that as a pb, we have prefixes to make it easier. I'd suggest to stay like that.

**Comment by anaigmo** [comment]
This makes reference to what we discuss in the issue #56, that we decided to go for option (3) bc we can differenciate each resource per module but keep same w3id base IRI avoiding the use of multiple prefixes within the mapping. But anyway if you think we should go for other option please comment in that issue so we can continue the discussion

**Comment by andimou** [comment]
> rmlst = http://w3id.org/rml/source-target/

could we perhaps call this `rmld = http://w3id.org/rml/data/` to be shorter?

**Comment by chrdebru** [comment]
`rmlcc = http://w3id.org/rml/collections-containers/`

could be replaced by `rmlcc = http://w3id.org/rml/cc/` to make it shorter.

**Comment by chrdebru** [comment]
> > rmlst = http://w3id.org/rml/source-target/
> 
> could we perhaps call this `rmld = http://w3id.org/rml/data/` to be shorter?

Source and target have an explicit notion of input and output streams, so I fear "data" as such could be misleading. Could it be called `io`? As it is abstract, it can leave room for various sources and targets.

**Comment by andimou** [comment]
if the collections-containers is shortened like this, then the source-target could as well become:

**Comment by DylanVanAssche** [comment]
> Could it be called io

I like this for Source & Target!

**Comment by dachafra** [comment]
> Source and target have an explicit notion of input and output streams, so I fear "data" as such could be misleading. Could it be called io? As it is abstract, it can leave room for various sources and targets.

+1 for the io!

**Comment by bjdmeest** [comment]
I assumed that http://w3id.org/rml/ will have prefix `rml` and all resources will be addressable using prefix `rml`, so that you don't need to import 6 prefixes if you want to write RML, is that assumption still correct?

**Comment by andimou** [comment]
I thought that during our latest discussions we agreed on having different namespaces for different modules. This way if one module needs an update, the rest are not affected. If we go for different namespaces, as a consequence prefixes are different.
