### ISSUE TITLE
parent and child terminology

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#59]
R2RML specification names the `rr:parent` and `rr:child` as _parent query_ and _child query_, would we keep this terminology?

Or should we skip the query part and keep them only _parent_ and _child_? I have the impression when we talk we typically use these terms.

or something else? if so, what?

**Comment by pmaria** [comment]
I believe it's called _parent column_ and _child column_ right now. I think we should change this to _parent expression_ and _child expression_. I think this matches well with the proposal in #53

**Comment by bjdmeest** [comment]
To fully match with #53, I'd suggest to use the names `rml:parentMap` and `rml:childMap` to refer to _parent expression_ and _child expression_, and maybe have `rml:parent` and `rml:child` as their _reference shortcut property_ (so they actually refer to _parent reference_ and _child reference_).

If we don't do that I assume the most simple join will be of form below, as an _expression_ means that the object should be an ExpressionMap?

```turtle
ex:po rml:joincondition [
  rml:child [
    rml:reference "foreignId"
  ] ;
  rml:parent [
    rml:reference "Id"
  ]
] .
```

**Comment by anaigmo** [comment]
Oki, then summing up the proposed changes in this issue:
* Add two subclasses of `:ExpressionMap`: `:ParentMap` and `:ChildMap`
* Add two new properties: `:parentMap` and `:childMap`; adjusting `:parent` and `:child` to be the shortcuts

Then instead of:
> ```turtle
> ex:po rml:joincondition [
>   rml:child [
>     rml:reference "foreignId"
>   ] ;
>   rml:parent [
>     rml:reference "Id"
>   ]
> ] .
> ```

We would have **without shortcuts**:
```turtle
ex:po rml:joincondition [
  rml:childMap [
    rml:reference "foreignId"
  ] ;
  rml:parentMap [
    rml:reference "Id"
  ]
] .
```

And **with shortcuts**:
```turtle
ex:po rml:joincondition [
  rml:child "foreignId";
  rml:parent "Id"
] .
```

**Comment by DylanVanAssche** [comment]
This issue had a proposal and is done. Closing.
