### ISSUE TITLE
Mistakes in the shapes

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-core#75]
- [ ] rml:cartessianProduct should be rml:cartesianProduct (2 occurences)
- [ ] The message for RMLLanguageMapShape seems incorrect: "rml:LanguageMap must specify an rml:template or rml:constant with the IRI of the language." --> Languages do not have an IRI.

**Comment by DylanVanAssche** [comment]
>  The message for RMLLanguageMapShape seems incorrect: "rml:LanguageMap must specify an rml:template or rml:constant with the IRI of the language." --> Languages do not have an IRI.

I fail to understand why they cannot have an IRI?
You can do the following:

```
... rml:language <#MyLanguageMap>;


<#MyLanguageMap>
  rml:reference "language_tag";
```

**Comment by chrdebru** [comment]
Isn't `rml:language` used for constants?

**Comment by DylanVanAssche** [comment]
Oh yeah I meant `rml:languageMap`, fixed the example

**Comment by DylanVanAssche** [comment]
Ah you mean the last thing, I see!

**Comment by chrdebru** [comment]
rml:LanguageMap must specify an rml:template, rml:reference, or rml:constant with the ISOXXX code of the language.

--> references are also allowed, no?

**Comment by DylanVanAssche** [comment]
That's added yes now, see PR
