### ISSUE TITLE
Joins in RML

### ISSUE THREAD

**Issue by andimou** [kg-construct/rml-core#76]
How joins are currently handled: 

We refer to a Parent Triples Map but in fact we use the Subject Map of the Triples Map.

```
<#TM1> 
    rml:logicalSource <LS1> ;
    rml:subjectMap <#SM1> ;
    rml:predicateObjectMap [
        rml:predicateMap <#PM1> ;
        rml:objectMap [ rml:parentTriplesMap <#SM2> ] ]. 

<#TM2> 
    rml:logicalSource <LS2> ;
    rml:subjectMap <#SM2> ;
    rml:predicateObjectMap [
        rml:predicateMap <#PM2> ;
        rml:objectMap <#OM2> ] .
```

**Limitations**:

This limits us because a Subject Map can only be an IRI or a Blank Node but it cannot be a literal.

It also limits us as we can only join the object of the one triple with the subject of another triple.

**Solution**:
Actually refer to the RDF term which we want to reuse instead of the Triples Map. 

In this case, the above would become: 
 
```
<#TM1> 
    rml:logicalSource <LS1> ;
    rml:subjectMap <#SM1> ;
    rml:predicateObjectMap [
        rml:predicateMap <#PM1> ;
        rml:objectMap [ rml:parentTermMap <#SM2> ] ]. 

<#TM2> 
    rml:logicalSource <LS2> ;
    rml:subjectMap <#SM2> ;
    rml:predicateObjectMap [
        rml:predicateMap <#PM2> ;
        rml:objectMap <#OM2> ] .
```

(`rml:parentTermMap` would be introduced to refer to the Term we want to reuse)

We can reuse the above to even refer to the object of `<#TM2>`, e.g.:
```
<#TM1> 
    rml:logicalSource <LS1> ;
    rml:subjectMap <#SM1> ;
    rml:predicateObjectMap [
        rml:predicateMap <#PM1> ;
        rml:objectMap [ rml:parentTermMap <#OM2> ] ]. 

<#TM2> 
    rml:logicalSource <LS2> ;
    rml:subjectMap <#SM2> ;
    rml:predicateObjectMap [
        rml:predicateMap <#PM2> ;
        rml:objectMap <#OM2> ] .
```

and we can do that in any Term Map, e.g., in the following we join the Subject Map of the one TM with the Subject Map of the other TM:

```
<#TM1> 
    rml:logicalSource <LS1> ;
    rml:subjectMap [ rml:parentTermMap <#SM2> ] ;

<#TM2> 
    rml:logicalSource <LS2> ;
    rml:subjectMap <#SM2> .
```

That proposal would solve the issues with joins for literals but not the cases where we want to use data from two data sources as in kg-construct/rml-jc#3.

**Comment by dachafra** [comment]
This discussion was previous to RML-lv and it's now outdated. As @elsdvlee suggested, it can be closed.
