### ISSUE TITLE
How to handle programming language specific datatypes?

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/rml-core#8]

**Comment by andimou** [comment]
do we have an associated use case for this issue?

**Comment by bjdmeest** [comment]
It's an issue that came from @pmaria at https://kg-construct.slack.com/archives/C01QFSW77QF/p1616769440004400?thread_ts=1616768778.002200&cid=C01QFSW77QF , Pano, do you know whether there's an existing use case for this?

**Comment by bjdmeest** [comment]
It came for #6, so also from a Slack discussion. @pmaria do you have a use case in mind?

**Comment by pmaria** [comment]
Similar to #9:

The use case here would be that value types (e.g. dates or booleans, etc.) of values resulting from functions could be used as is, without having to specify termtype or datatype.

**Comment by bjdmeest** [comment]
This is a duplicate from #9, closing
