### ISSUE TITLE
What about referencing object/term maps

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-core#82]
The issue on joins is closed and a "referencing term maps" spec is mentioned, but where is it? The problem being is that the test cases still contain joins and some details need to be worked out.

**Comment by DylanVanAssche** [comment]
The ReferenceObjectMap was kept as far as I know, so it should not change much in RML Core.

Please confirm @elsdvlee and @pmaria

**Comment by dachafra** [comment]
This is already integrated into #74 and #78. I'm going to close the issue but please feel free to open it again if I missed something @chrdebru @elsdvlee
