### ISSUE TITLE
Details lacking in datatype map

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-core#86]
Datatype maps generate IRIs, but it does not describe the (very unlikely) case where one wants to generate bespoke datatype IRIs (which is allowed, look at geosparql, for intsance). So, what happens when we have:

```[] rml:objectMap [
  rml:reference "value" ;
  rml:datatypeMap [
    rml:template "foo/{datatype}" ;
  ] ;
] .
```
Shall we follow the same rule for generating IRIs? If absolute, keep it, if not, try see if base IRI plus value is an absolute IRI?

**Comment by DylanVanAssche** [comment]
I would use the same thing as with regular IRIs. A DataTypeMap is the same as any other Expression Map IMO. Of course you can generate nonsense things here... I guess you cannot prevent that.

**Comment by dachafra** [comment]
> I would use the same thing as with regular IRIs.
